services:
  - type: web
    name: amahle-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

databases:
  - name: amahle-postgres
    plan: free
    ipAllowList: []

envVarGroups:
  - name: database
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: amahle-postgres
          property: connectionString
