services:
  - type: web
    name: amahle-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true

